### ISSUE TITLE
React v16

### ISSUE THREAD

**Issue by montyclt** [cleandart/react-dart#137]
React v16 was released on Sept 2017.

There are plans to update?

https://reactjs.org/blog/2017/09/26/react-v16.0.html

**Comment by aaronlademann-wf** [comment]
@montyclt @nsreenath to clarify... it is on our roadmap, but our priority right now is ensuring that this library will work with the upcoming Dart 2 SDK.

We are wary of making those changes - AND implementing support for the ReactJS 16 API simultaneously.

**Comment by aloisdeniel** [comment]
Any news ? 

Would love to share code with Flutter, but I need Dart 2 support. :(

**Comment by graphicbeacon** [comment]
Hey friends, love the work you've done so far on this. Any news on this update?

**Comment by aaronlademann-wf** [comment]
@aloisdeniel react-dart is fully compatible with Dart 2 as of [version `4.5.0`](https://github.com/cleandart/react-dart/pull/150).

@graphicbeacon work for the React 16 upgrade will begin this quarter - but will likely not reach production until late in the quarter / early q2 (April-ish).

We have some big improvements coming to how props / state maps are handled as well - so that the ReactJS dev tools will be fully compatible with the JS produced by react-dart.

cc/ @greglittlefield-wf

**Comment by graphicbeacon** [comment]
@aaronlademann-wf Thanks for clarifying. Really looking forward to this.

**Comment by knopp** [comment]
This would be very nice to have. We're starting a new project and would very much like to do it with React 16. Are there any updates on possible timeline?

**Comment by aaronlademann-wf** [comment]
React 16 is supported in 5.0.0-alpha.0 / 5.0.0-alpha.1, and will be released as 5.0.0 stable today @knopp @graphicbeacon @montyclt.
