### ISSUE TITLE
How to use style generator func in class dart component? 

### ISSUE THREAD

**Issue by Atom735** [cleandart/react-dart#279]
[**I tryed to rewrite**](https://github.com/Atom735/dart-mui/blob/master/example/sign-in.dart) [Sign-in template](https://github.com/mui-org/material-ui/blob/master/docs/src/pages/getting-started/templates/sign-in/SignIn.js) from [Material-UI][material] with dart... And i had a problem with **JSS**... [Material-UI][material] had a function `makeStyles`, who return function of style generator. I need to get class names and need to study work with it. How i can link it function with my class-component and use him members in props?

[material]: https://material-ui.com/

**Comment by aaronlademann-wf** [comment]
`makeStyles` is a custom hook within the Mui JS library and is outside the scope of what this library supports. It would require a JS interop layer to handle the css-in-js engine that the Mui JS components make use of.

The hooks in this library allow you to write React function components in Dart. They do not make it so that you can make use of hooks written in JS components.
