### ISSUE TITLE
suggestions / examples for testing React dart code?

### ISSUE THREAD

**Issue by trentgrover-wf** [cleandart/react-dart#33]
Outside of Dart, I usually use the react-addons lib for testing react code.  Is there anything comparable available within the Dart environment?  Do you have any suggestions as to how best to test react-dart code?

**Comment by hleumas** [comment]
You can include `react_test` and then call `setTestConfiguration()`. This way your react components will render into `MarkupDescription` instead of real components. Then you can manually create an instance of component and initialize it through `initializeComponent` and finally, call `render` manually and check the output.

It is far from being easy to use. If you would be willing to improve it anyhow, your pull requests are welcome!

**Comment by basheps** [comment]
'render into MarkupDescription instead of real components'... Can you give an example of this.
