### ISSUE TITLE
Upgrade to v 0.13.3 of React

### ISSUE THREAD

**Issue by hleumas** [cleandart/react-dart#47]

**Comment by danschultz** [comment]
:+1:

**Comment by greglittlefield-wf** [comment]
Yay, glad to hear about 0.13 support!

I've been preemptively playing around with 0.13 along with react-dart a bit, mostly due to [0.13's addition of `cloneElement`](https://facebook.github.io/react/blog/2015/03/03/react-v0.13-rc2.html#react.cloneelement).

Are there any plans to include some of the [top-level API methods](https://facebook.github.io/react/docs/top-level-api.html) like `cloneElement` in the Dart wrapper? Would that be a react-dart separate issue?

---

Here's [a diff](https://github.com/cleandart/react-dart/compare/cleandart:04952f24a4c122e44313757e29d56810d040d1c0...greglittlefield-wf:cloneElement?expand=1#diff-12ac054bb8b76f35c1035afef1d94396R71) of some of the changes I made to get `cloneElement` working (and [the cloneElement implementation](https://github.com/cleandart/react-dart/compare/cleandart:04952f24a4c122e44313757e29d56810d040d1c0...greglittlefield-wf:cloneElement?expand=1#diff-12ac054bb8b76f35c1035afef1d94396R71)) in the diff) for reference. Feel free to incorporate any part of that work!

**Comment by matystl** [comment]
right now we did findDOMNode(https://github.com/cleandart/react-dart/pull/50) implementation. But i agree that having cloneElement would be nice to add.

**Comment by hleumas** [comment]
Closing this issue now. Let's move the discussion about `cloneElement` support to #52 .
