### ISSUE TITLE
use named parameters?

### ISSUE THREAD

**Issue by sethladd** [cleandart/react-dart#53]
What do you think about:

```
div(className: "somehing", children: [
  h1(style: style(height: "20px"), "Headline"),
  a(href:"something.com", "Something"),
  "Some text"
])
```

instead of

```
div({"className": "somehing"}, [
  h1({"style": {"height": "20px"}}, "Headline"),
  a({"href":"something.com"}, "Something"),
  "Some text"
])
```

?

**Comment by hleumas** [comment]
Hi @sethladd,

I am not sure what are the benefits of this. I see at only as a little bit different syntax and that is not enough to outweight the cons I see:

1. In React, you can easily access all of your props as a simple `Map` structure. This is convenient because it allows you to manipulate them using standard map operations and through functions operating on top of `Map`. I actually dislike the OOP way of masking standard data structures like List and Map by some fancy objects. It feals like building the Babel tower. 

As Alan Peris said:
"It is better to have 100 functions operate on one data structure than to have 10 functions operate on 10 data structures."

2. The set of valid props for elements is not limited. This would mean that Mirrors would be needed to make this happen and I really don't understand Mirrors performance implications.

**Comment by sethladd** [comment]
The benefit would be better code completion and static warnings when you misspell something.

Compare:

```
div({'styl': 'color:red'});
```

with

```
div(styl: 'color:red');
```

The second one will have a warning, and you'll be able to code complete the options.

**Comment by wstrange** [comment]
+1  :-)

**Comment by hleumas** [comment]
@sethladd thanks for pointing out the benefits. Unfortunately, I don't see way to overcome obstacles I mentioned in previous comment.

**Comment by jonaskello** [comment]
+1 for the typed version. I am currently working on making a typed Dart wrapper for [react-bootstrap](http://react-bootstrap.github.io/). For this I am using the approach suggested by @sethladd. It is a work in progress but for reference, the repo is [here](https://github.com/jonaskello/react_bootstrap). The main benefit is that you can easily check what props are available. In theory you should be able to get parameters for each bootstrap component listed in Webstorm but seems it does not work at the moment. Possibly because of the return value being a typedef.

**Comment by aaronlademann-wf** [comment]
@sethladd @wstrange @jonaskello 

Workiva's UI Platform Team (@greglittlefield-wf specifically) has developed an API for strongly typed React-dart components, and we will be open-sourcing it soon!

**Comment by DanTup** [comment]
> In React, you can easily access all of your props as a simple Map structure. This is convenient because it allows you to manipulate them using standard map operations and through functions operating on top of Map. I actually dislike the OOP way of masking standard data structures like List and Map by some fancy objects. It feels like building the Babel tower.

One of the main attractions to Dart is types, so I'm surprised you don't miss them here! If I was going to use React in Dart I was absolutely want strong typing of Props etc.

One of my colleagues created bindings for us to use React from Bridge.NET (a C#-to-javascript transpiler):

https://github.com/ProductiveRage/Bridge.React

There's an example on that page; the Props classes are nested within the components; all access to them is completely typed (and refactorable etc). Maybe worth a look :)

**Comment by kasperpeulen** [comment]
@aaronlademann-wf Are you still planning to open source it? I'm curious!

**Comment by aaronlademann-wf** [comment]
@kasperpeulen @DanTup it hasn't been prioritized, but it is still planned, yes.

**Comment by aaronlademann-wf** [comment]
@kasperpeulen @DanTup @sethladd @wstrange @jonaskello @hleumas 

@greglittlefield-wf will be speaking at [Dart Summit 2016](https://events.dartlang.org/2016/summit/) in Germany (Thursday, October 27th) about "Getting the most out of React in Dart".  As part of that, he'll be announcing our framework for building statically-typed React UI components with Dart _(new OSS repo)_.

The wait is almost over!

cc/ @joelleibow-wf @trentgrover-wf

**Comment by aaronlademann-wf** [comment]
@kasperpeulen @DanTup @sethladd @wstrange @jonaskello @hleumas 

The wait is over.  Workiva's Dart library for building statically-typed React UI components is public, and available on pub.dartlang.org!

https://workiva.github.io/over_react/

**Comment by sethladd** [comment]
Congrats!
